name: Create Lambda instance for Java API

on:
  pull_request:
    types: opened
    branches:
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Region from tfvars
        run: |
          export REGION=$(grep 'region' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Region: $REGION"
          echo "REGION=$REGION" >> $GITHUB_ENV

      - name: Set up AWS Cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get Description from pull request
        run: |
          export DESCRIPTION=$(echo "${{ github.event.pull_request.body }}")
          echo "Description: $DESCRIPTION"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Get Destroy infra from tfvars
        run: |
          export DESTROY_INFRA=$(cat infra/terraform.tfvars | grep destroy_infra | cut -d'=' -f2 | tr -d '[:space:]')
          echo "Destroy Infra: $DESTROY_INFRA"
          echo "DESTROY_INFRA=$DESTROY_INFRA" >> $GITHUB_ENV

      - name: Destroy infra if variable is set
        if: ${{ env.DESTROY_INFRA == 'true' }}
        run: |
          cd infra
          terraform init
          terraform destroy -auto-approve

      - name: Get Lambda function name
        run: |
          export LAMBDA_NAME=$(grep 'function_name' infra/main.tf | cut -d'"' -f2)
          echo "Lambda Name: $LAMBDA_NAME"
          echo "LAMBDA_NAME=$LAMBDA_NAME" >> $GITHUB_ENV

      - name: Create Lambda if destroy variable is not set
        if: ${{ env.DESTROY_INFRA != 'true' }}
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Set PR msg
        run: |
          echo "MSG=A lambda ${{ env.LAMBDA_NAME }} foi ${{ env.DESTROY_INFRA == 'true' && 'destruída' || 'criada' }} com sucesso!" >> $GITHUB_ENV

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: ${{ github.event.pull_request.number }},
              repo: context.repo.repo,
              body: `${{ env.MSG }}`
            })